### ISSUE TITLE
.net core 3.1 support

### ISSUE THREAD

**Issue by idanla-sim** [fruffin/serverless-dotnet#19]
Hi, could you please add support for .net core 3.1?
i think all that needs to be done is add `path.join(servicePath, `bin/${this.configuration}/netcoreapp3.1/publish/`)`
to sourcePath in pack.js

**Comment by leidsongermano** [comment]
> Hi, could you please add support for .net core 3.1?
> i think all that needs to be done is add `path.join(servicePath, `bin/${this.configuration}/netcoreapp3.1/publish/`)`
> to sourcePath in pack.js

https://github.com/leidsongermano/serverless-dotnet-packing

**Comment by fruffin** [comment]
This is now fixed in version 1.6.1
