### ISSUE TITLE
Doesn't Package Runtime DLLs Appropriatly

### ISSUE THREAD

**Issue by camhart** [fruffin/serverless-dotnet#2]
It appears AWS tools package up runtime DLL's slightly differently.  I'm not sure on the details but I'm having the issue and it's somewhat pointed out at http://stackoverflow.com/questions/41235714/im-building-a-c-sharp-aws-lambda-package-how-do-i-properly-include-system-data.

I'll keep looking into it.

Edit:

Looking at https://github.com/aws/aws-lambda-dotnet/blob/master/Libraries/src/Amazon.Lambda.Tools/DotNetCLIWrapper.cs, you'll see they've outlined a couple DLL's that need to get pulled in from the runtimes directory.

**Comment by camhart** [comment]
PR created
https://github.com/fruffin/serverless-dotnet/pull/3

**Comment by fruffin** [comment]
Thanks for the bug report and the PR. will publish a new version now
